name = "whatsapp-ai-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[site]
bucket = "public"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "WHATSAPP_MEDIA"
id = "YOUR_KV_NAMESPACE_ID"

[[d1_databases]]
binding = "DB"
database_name = "whatsapp_ai_db"
database_id = "YOUR_D1_DATABASE_ID"

[vars]
ENVIRONMENT = "production"


